// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: received_emails.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	nagomi "nagomi-core/internal/gen/nagomi/v1"
)

const insertReceivedEmail = `-- name: InsertReceivedEmail :exec
insert into received_emails (user_id, sender, subject, outcome, transaction_id, error, body)
values (
  $1::uuid,
  $2::text,
  $3::text,
  $4,
  $5::bigint,
  $6::text,
  $7::text
)
`

type InsertReceivedEmailParams struct {
	UserID        uuid.UUID           `db:"user_id" json:"user_id"`
	Sender        string              `db:"sender" json:"sender"`
	Subject       string              `db:"subject" json:"subject"`
	Outcome       nagomi.EmailOutcome `db:"outcome" json:"outcome"`
	TransactionID *int64              `db:"transaction_id" json:"transaction_id"`
	Error         *string             `db:"error" json:"error"`
	Body          *string             `db:"body" json:"body"`
}

func (q *Queries) InsertReceivedEmail(ctx context.Context, arg InsertReceivedEmailParams) error {
	_, err := q.db.Exec(ctx, insertReceivedEmail,
		arg.UserID,
		arg.Sender,
		arg.Subject,
		arg.Outcome,
		arg.TransactionID,
		arg.Error,
		arg.Body,
	)
	return err
}

const listReceivedEmails = `-- name: ListReceivedEmails :many
select id, user_id, received_at, sender, subject, outcome, transaction_id, error, body
from received_emails
where user_id = $1::uuid
order by received_at desc, id desc
`

func (q *Queries) ListReceivedEmails(ctx context.Context, userID uuid.UUID) ([]ReceivedEmail, error) {
	rows, err := q.db.Query(ctx, listReceivedEmails, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ReceivedEmail
	for rows.Next() {
		var i ReceivedEmail
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ReceivedAt,
			&i.Sender,
			&i.Subject,
			&i.Outcome,
			&i.TransactionID,
			&i.Error,
			&i.Body,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const trimReceivedEmails = `-- name: TrimReceivedEmails :exec
delete from received_emails
where user_id = $1::uuid
  and id not in (
    select id
    from received_emails
    where user_id = $1::uuid
    order by received_at desc, id desc
    limit $2::int
  )
`

type TrimReceivedEmailsParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Keep   int32     `db:"keep" json:"keep"`
}

func (q *Queries) TrimReceivedEmails(ctx context.Context, arg TrimReceivedEmailsParams) error {
	_, err := q.db.Exec(ctx, trimReceivedEmails, arg.UserID, arg.Keep)
	return err
}
