// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statements.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countExistingExternalIDs = `-- name: CountExistingExternalIDs :one
select
  count(*)
from
  transactions
where
  account_id = $1::bigint
  and external_id = any($2::text[])
`

type CountExistingExternalIDsParams struct {
	AccountID   int64    `db:"account_id" json:"account_id"`
	ExternalIds []string `db:"external_ids" json:"external_ids"`
}

func (q *Queries) CountExistingExternalIDs(ctx context.Context, arg CountExistingExternalIDsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExistingExternalIDs, arg.AccountID, arg.ExternalIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createStatement = `-- name: CreateStatement :one
insert into
  statements (
    user_id,
    status,
    file_path,
    file_hash,
    file_name,
    parser,
    bank,
    account_type,
    account_number,
    period_start,
    period_end,
    currency,
    opening_balance_cents,
    closing_balance_cents,
    line_count,
    parsed
  )
values
  (
    $1::uuid,
    $2::smallint,
    $3::text,
    $4::text,
    $5::text,
    $6::text,
    $7::text,
    $8::smallint,
    $9::text,
    $10::date,
    $11::date,
    $12::char(3),
    $13::bigint,
    $14::bigint,
    $15::int,
    $16::jsonb
  )
returning
  id, user_id, account_id, status, file_path, file_hash, file_name, parser, bank, account_type, account_number, period_start, period_end, currency, opening_balance_cents, closing_balance_cents, line_count, parsed, created_at, imported_at
`

type CreateStatementParams struct {
	UserID              uuid.UUID `db:"user_id" json:"user_id"`
	Status              int16     `db:"status" json:"status"`
	FilePath            string    `db:"file_path" json:"file_path"`
	FileHash            string    `db:"file_hash" json:"file_hash"`
	FileName            string    `db:"file_name" json:"file_name"`
	Parser              string    `db:"parser" json:"parser"`
	Bank                string    `db:"bank" json:"bank"`
	AccountType         int16     `db:"account_type" json:"account_type"`
	AccountNumber       string    `db:"account_number" json:"account_number"`
	PeriodStart         time.Time `db:"period_start" json:"period_start"`
	PeriodEnd           time.Time `db:"period_end" json:"period_end"`
	Currency            string    `db:"currency" json:"currency"`
	OpeningBalanceCents *int64    `db:"opening_balance_cents" json:"opening_balance_cents"`
	ClosingBalanceCents *int64    `db:"closing_balance_cents" json:"closing_balance_cents"`
	LineCount           int32     `db:"line_count" json:"line_count"`
	Parsed              []byte    `db:"parsed" json:"parsed"`
}

func (q *Queries) CreateStatement(ctx context.Context, arg CreateStatementParams) (Statement, error) {
	row := q.db.QueryRow(ctx, createStatement,
		arg.UserID,
		arg.Status,
		arg.FilePath,
		arg.FileHash,
		arg.FileName,
		arg.Parser,
		arg.Bank,
		arg.AccountType,
		arg.AccountNumber,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Currency,
		arg.OpeningBalanceCents,
		arg.ClosingBalanceCents,
		arg.LineCount,
		arg.Parsed,
	)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Status,
		&i.FilePath,
		&i.FileHash,
		&i.FileName,
		&i.Parser,
		&i.Bank,
		&i.AccountType,
		&i.AccountNumber,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Currency,
		&i.OpeningBalanceCents,
		&i.ClosingBalanceCents,
		&i.LineCount,
		&i.Parsed,
		&i.CreatedAt,
		&i.ImportedAt,
	)
	return i, err
}

const deleteStalePendingStatements = `-- name: DeleteStalePendingStatements :many
delete from statements
where
  status = 1
  and created_at < $1::timestamptz
returning
  file_path
`

func (q *Queries) DeleteStalePendingStatements(ctx context.Context, before time.Time) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteStalePendingStatements, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_path string
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteStatement = `-- name: DeleteStatement :one
delete from statements
where
  id = $1::bigint
  and user_id = $2::uuid
returning
  file_path
`

type DeleteStatementParams struct {
	ID     int64     `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteStatement(ctx context.Context, arg DeleteStatementParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteStatement, arg.ID, arg.UserID)
	var file_path string
	err := row.Scan(&file_path)
	return file_path, err
}

const deleteStatementTransactions = `-- name: DeleteStatementTransactions :execrows
delete from transactions t
using statements s
where
  t.statement_id = s.id
  and s.id = $1::bigint
  and s.user_id = $2::uuid
`

type DeleteStatementTransactionsParams struct {
	ID     int64     `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteStatementTransactions(ctx context.Context, arg DeleteStatementTransactionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStatementTransactions, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStatement = `-- name: GetStatement :one
select
  s.id, s.user_id, s.account_id, s.status, s.file_path, s.file_hash, s.file_name, s.parser, s.bank, s.account_type, s.account_number, s.period_start, s.period_end, s.currency, s.opening_balance_cents, s.closing_balance_cents, s.line_count, s.parsed, s.created_at, s.imported_at,
  a.name as account_name
from
  statements s
  left join accounts a on a.id = s.account_id
where
  s.id = $1::bigint
  and s.user_id = $2::uuid
`

type GetStatementParams struct {
	ID     int64     `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type GetStatementRow struct {
	Statement   Statement `db:"statement" json:"statement"`
	AccountName *string   `db:"account_name" json:"account_name"`
}

func (q *Queries) GetStatement(ctx context.Context, arg GetStatementParams) (GetStatementRow, error) {
	row := q.db.QueryRow(ctx, getStatement, arg.ID, arg.UserID)
	var i GetStatementRow
	err := row.Scan(
		&i.Statement.ID,
		&i.Statement.UserID,
		&i.Statement.AccountID,
		&i.Statement.Status,
		&i.Statement.FilePath,
		&i.Statement.FileHash,
		&i.Statement.FileName,
		&i.Statement.Parser,
		&i.Statement.Bank,
		&i.Statement.AccountType,
		&i.Statement.AccountNumber,
		&i.Statement.PeriodStart,
		&i.Statement.PeriodEnd,
		&i.Statement.Currency,
		&i.Statement.OpeningBalanceCents,
		&i.Statement.ClosingBalanceCents,
		&i.Statement.LineCount,
		&i.Statement.Parsed,
		&i.Statement.CreatedAt,
		&i.Statement.ImportedAt,
		&i.AccountName,
	)
	return i, err
}

const getStatementByHash = `-- name: GetStatementByHash :one
select
  id, user_id, account_id, status, file_path, file_hash, file_name, parser, bank, account_type, account_number, period_start, period_end, currency, opening_balance_cents, closing_balance_cents, line_count, parsed, created_at, imported_at
from
  statements
where
  user_id = $1::uuid
  and file_hash = $2::text
`

type GetStatementByHashParams struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	FileHash string    `db:"file_hash" json:"file_hash"`
}

func (q *Queries) GetStatementByHash(ctx context.Context, arg GetStatementByHashParams) (Statement, error) {
	row := q.db.QueryRow(ctx, getStatementByHash, arg.UserID, arg.FileHash)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Status,
		&i.FilePath,
		&i.FileHash,
		&i.FileName,
		&i.Parser,
		&i.Bank,
		&i.AccountType,
		&i.AccountNumber,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Currency,
		&i.OpeningBalanceCents,
		&i.ClosingBalanceCents,
		&i.LineCount,
		&i.Parsed,
		&i.CreatedAt,
		&i.ImportedAt,
	)
	return i, err
}

const listStatements = `-- name: ListStatements :many
select
  s.id, s.user_id, s.account_id, s.status, s.file_path, s.file_hash, s.file_name, s.parser, s.bank, s.account_type, s.account_number, s.period_start, s.period_end, s.currency, s.opening_balance_cents, s.closing_balance_cents, s.line_count, s.parsed, s.created_at, s.imported_at,
  a.name as account_name
from
  statements s
  left join accounts a on a.id = s.account_id
where
  s.user_id = $1::uuid
  and (
    $2::bigint is null
    or s.account_id = $2::bigint
  )
  and (
    $3::smallint is null
    or s.status = $3::smallint
  )
order by
  s.period_start desc,
  s.id desc
`

type ListStatementsParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	AccountID *int64    `db:"account_id" json:"account_id"`
	Status    *int16    `db:"status" json:"status"`
}

type ListStatementsRow struct {
	Statement   Statement `db:"statement" json:"statement"`
	AccountName *string   `db:"account_name" json:"account_name"`
}

func (q *Queries) ListStatements(ctx context.Context, arg ListStatementsParams) ([]ListStatementsRow, error) {
	rows, err := q.db.Query(ctx, listStatements, arg.UserID, arg.AccountID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatementsRow
	for rows.Next() {
		var i ListStatementsRow
		if err := rows.Scan(
			&i.Statement.ID,
			&i.Statement.UserID,
			&i.Statement.AccountID,
			&i.Statement.Status,
			&i.Statement.FilePath,
			&i.Statement.FileHash,
			&i.Statement.FileName,
			&i.Statement.Parser,
			&i.Statement.Bank,
			&i.Statement.AccountType,
			&i.Statement.AccountNumber,
			&i.Statement.PeriodStart,
			&i.Statement.PeriodEnd,
			&i.Statement.Currency,
			&i.Statement.OpeningBalanceCents,
			&i.Statement.ClosingBalanceCents,
			&i.Statement.LineCount,
			&i.Statement.Parsed,
			&i.Statement.CreatedAt,
			&i.Statement.ImportedAt,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStatementImported = `-- name: MarkStatementImported :one
update statements
set
  status = 2,
  account_id = $1::bigint,
  imported_at = now()
where
  id = $2::bigint
  and user_id = $3::uuid
  and status = 1
returning
  id, user_id, account_id, status, file_path, file_hash, file_name, parser, bank, account_type, account_number, period_start, period_end, currency, opening_balance_cents, closing_balance_cents, line_count, parsed, created_at, imported_at
`

type MarkStatementImportedParams struct {
	AccountID int64     `db:"account_id" json:"account_id"`
	ID        int64     `db:"id" json:"id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) MarkStatementImported(ctx context.Context, arg MarkStatementImportedParams) (Statement, error) {
	row := q.db.QueryRow(ctx, markStatementImported, arg.AccountID, arg.ID, arg.UserID)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Status,
		&i.FilePath,
		&i.FileHash,
		&i.FileName,
		&i.Parser,
		&i.Bank,
		&i.AccountType,
		&i.AccountNumber,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Currency,
		&i.OpeningBalanceCents,
		&i.ClosingBalanceCents,
		&i.LineCount,
		&i.Parsed,
		&i.CreatedAt,
		&i.ImportedAt,
	)
	return i, err
}
