// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: statements.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const confirmStatementTransaction = `-- name: ConfirmStatementTransaction :exec
update transactions
set
  tx_date = $1::timestamptz,
  tx_amount_cents = $2::bigint,
  tx_desc = $3::text,
  exchange_rate = coalesce($4::double precision, exchange_rate),
  external_id = $5::text,
  statement_id = $6::bigint,
  source = $7::smallint
where
  id = $8::bigint
  and account_id = $9::bigint
`

type ConfirmStatementTransactionParams struct {
	TxDate        time.Time `db:"tx_date" json:"tx_date"`
	TxAmountCents int64     `db:"tx_amount_cents" json:"tx_amount_cents"`
	TxDesc        string    `db:"tx_desc" json:"tx_desc"`
	ExchangeRate  *float64  `db:"exchange_rate" json:"exchange_rate"`
	ExternalID    string    `db:"external_id" json:"external_id"`
	StatementID   int64     `db:"statement_id" json:"statement_id"`
	Source        int16     `db:"source" json:"source"`
	ID            int64     `db:"id" json:"id"`
	AccountID     int64     `db:"account_id" json:"account_id"`
}

func (q *Queries) ConfirmStatementTransaction(ctx context.Context, arg ConfirmStatementTransactionParams) error {
	_, err := q.db.Exec(ctx, confirmStatementTransaction,
		arg.TxDate,
		arg.TxAmountCents,
		arg.TxDesc,
		arg.ExchangeRate,
		arg.ExternalID,
		arg.StatementID,
		arg.Source,
		arg.ID,
		arg.AccountID,
	)
	return err
}

const createStatement = `-- name: CreateStatement :one
insert into
  statements (
    user_id,
    status,
    file_path,
    file_hash,
    file_name,
    parser,
    bank,
    account_type,
    account_number,
    period_start,
    period_end,
    currency,
    opening_balance_cents,
    closing_balance_cents,
    balance_ok,
    line_count,
    parsed
  )
values
  (
    $1::uuid,
    $2::smallint,
    $3::text,
    $4::text,
    $5::text,
    $6::text,
    $7::text,
    $8::smallint,
    $9::text,
    $10::date,
    $11::date,
    $12::char(3),
    $13::bigint,
    $14::bigint,
    $15::boolean,
    $16::int,
    $17::jsonb
  )
returning
  id, user_id, account_id, status, file_path, file_hash, file_name, parser, bank, account_type, account_number, period_start, period_end, currency, opening_balance_cents, closing_balance_cents, line_count, parsed, created_at, imported_at, balance_ok
`

type CreateStatementParams struct {
	UserID              uuid.UUID `db:"user_id" json:"user_id"`
	Status              int16     `db:"status" json:"status"`
	FilePath            string    `db:"file_path" json:"file_path"`
	FileHash            string    `db:"file_hash" json:"file_hash"`
	FileName            string    `db:"file_name" json:"file_name"`
	Parser              string    `db:"parser" json:"parser"`
	Bank                string    `db:"bank" json:"bank"`
	AccountType         int16     `db:"account_type" json:"account_type"`
	AccountNumber       string    `db:"account_number" json:"account_number"`
	PeriodStart         time.Time `db:"period_start" json:"period_start"`
	PeriodEnd           time.Time `db:"period_end" json:"period_end"`
	Currency            string    `db:"currency" json:"currency"`
	OpeningBalanceCents *int64    `db:"opening_balance_cents" json:"opening_balance_cents"`
	ClosingBalanceCents *int64    `db:"closing_balance_cents" json:"closing_balance_cents"`
	BalanceOk           *bool     `db:"balance_ok" json:"balance_ok"`
	LineCount           int32     `db:"line_count" json:"line_count"`
	Parsed              []byte    `db:"parsed" json:"parsed"`
}

func (q *Queries) CreateStatement(ctx context.Context, arg CreateStatementParams) (Statement, error) {
	row := q.db.QueryRow(ctx, createStatement,
		arg.UserID,
		arg.Status,
		arg.FilePath,
		arg.FileHash,
		arg.FileName,
		arg.Parser,
		arg.Bank,
		arg.AccountType,
		arg.AccountNumber,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Currency,
		arg.OpeningBalanceCents,
		arg.ClosingBalanceCents,
		arg.BalanceOk,
		arg.LineCount,
		arg.Parsed,
	)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Status,
		&i.FilePath,
		&i.FileHash,
		&i.FileName,
		&i.Parser,
		&i.Bank,
		&i.AccountType,
		&i.AccountNumber,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Currency,
		&i.OpeningBalanceCents,
		&i.ClosingBalanceCents,
		&i.LineCount,
		&i.Parsed,
		&i.CreatedAt,
		&i.ImportedAt,
		&i.BalanceOk,
	)
	return i, err
}

const deleteStalePendingStatements = `-- name: DeleteStalePendingStatements :many
delete from statements
where
  status = 1
  and created_at < $1::timestamptz
returning
  file_path
`

func (q *Queries) DeleteStalePendingStatements(ctx context.Context, before time.Time) ([]string, error) {
	rows, err := q.db.Query(ctx, deleteStalePendingStatements, before)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var file_path string
		if err := rows.Scan(&file_path); err != nil {
			return nil, err
		}
		items = append(items, file_path)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const deleteStatement = `-- name: DeleteStatement :one
delete from statements
where
  id = $1::bigint
  and user_id = $2::uuid
returning
  file_path
`

type DeleteStatementParams struct {
	ID     int64     `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteStatement(ctx context.Context, arg DeleteStatementParams) (string, error) {
	row := q.db.QueryRow(ctx, deleteStatement, arg.ID, arg.UserID)
	var file_path string
	err := row.Scan(&file_path)
	return file_path, err
}

const deleteStatementTransactions = `-- name: DeleteStatementTransactions :execrows
delete from transactions t
using statements s
where
  t.statement_id = s.id
  and s.id = $1::bigint
  and s.user_id = $2::uuid
`

type DeleteStatementTransactionsParams struct {
	ID     int64     `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteStatementTransactions(ctx context.Context, arg DeleteStatementTransactionsParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteStatementTransactions, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getStatement = `-- name: GetStatement :one
select
  s.id, s.user_id, s.account_id, s.status, s.file_path, s.file_hash, s.file_name, s.parser, s.bank, s.account_type, s.account_number, s.period_start, s.period_end, s.currency, s.opening_balance_cents, s.closing_balance_cents, s.line_count, s.parsed, s.created_at, s.imported_at, s.balance_ok,
  a.name as account_name
from
  statements s
  left join accounts a on a.id = s.account_id
where
  s.id = $1::bigint
  and s.user_id = $2::uuid
`

type GetStatementParams struct {
	ID     int64     `db:"id" json:"id"`
	UserID uuid.UUID `db:"user_id" json:"user_id"`
}

type GetStatementRow struct {
	Statement   Statement `db:"statement" json:"statement"`
	AccountName *string   `db:"account_name" json:"account_name"`
}

func (q *Queries) GetStatement(ctx context.Context, arg GetStatementParams) (GetStatementRow, error) {
	row := q.db.QueryRow(ctx, getStatement, arg.ID, arg.UserID)
	var i GetStatementRow
	err := row.Scan(
		&i.Statement.ID,
		&i.Statement.UserID,
		&i.Statement.AccountID,
		&i.Statement.Status,
		&i.Statement.FilePath,
		&i.Statement.FileHash,
		&i.Statement.FileName,
		&i.Statement.Parser,
		&i.Statement.Bank,
		&i.Statement.AccountType,
		&i.Statement.AccountNumber,
		&i.Statement.PeriodStart,
		&i.Statement.PeriodEnd,
		&i.Statement.Currency,
		&i.Statement.OpeningBalanceCents,
		&i.Statement.ClosingBalanceCents,
		&i.Statement.LineCount,
		&i.Statement.Parsed,
		&i.Statement.CreatedAt,
		&i.Statement.ImportedAt,
		&i.Statement.BalanceOk,
		&i.AccountName,
	)
	return i, err
}

const getStatementByHash = `-- name: GetStatementByHash :one
select
  id, user_id, account_id, status, file_path, file_hash, file_name, parser, bank, account_type, account_number, period_start, period_end, currency, opening_balance_cents, closing_balance_cents, line_count, parsed, created_at, imported_at, balance_ok
from
  statements
where
  user_id = $1::uuid
  and file_hash = $2::text
`

type GetStatementByHashParams struct {
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
	FileHash string    `db:"file_hash" json:"file_hash"`
}

func (q *Queries) GetStatementByHash(ctx context.Context, arg GetStatementByHashParams) (Statement, error) {
	row := q.db.QueryRow(ctx, getStatementByHash, arg.UserID, arg.FileHash)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Status,
		&i.FilePath,
		&i.FileHash,
		&i.FileName,
		&i.Parser,
		&i.Bank,
		&i.AccountType,
		&i.AccountNumber,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Currency,
		&i.OpeningBalanceCents,
		&i.ClosingBalanceCents,
		&i.LineCount,
		&i.Parsed,
		&i.CreatedAt,
		&i.ImportedAt,
		&i.BalanceOk,
	)
	return i, err
}

const linkStatementTransactions = `-- name: LinkStatementTransactions :exec
update transactions
set statement_id = $1::bigint
where
  account_id = $2::bigint
  and external_id = any($3::text[])
  and statement_id is null
`

type LinkStatementTransactionsParams struct {
	StatementID int64    `db:"statement_id" json:"statement_id"`
	AccountID   int64    `db:"account_id" json:"account_id"`
	ExternalIds []string `db:"external_ids" json:"external_ids"`
}

// lines kept from a statement that was deleted without its transactions
func (q *Queries) LinkStatementTransactions(ctx context.Context, arg LinkStatementTransactionsParams) error {
	_, err := q.db.Exec(ctx, linkStatementTransactions, arg.StatementID, arg.AccountID, arg.ExternalIds)
	return err
}

const listExistingExternalIDs = `-- name: ListExistingExternalIDs :many
select
  external_id::text
from
  transactions
where
  account_id = $1::bigint
  and external_id = any($2::text[])
`

type ListExistingExternalIDsParams struct {
	AccountID   int64    `db:"account_id" json:"account_id"`
	ExternalIds []string `db:"external_ids" json:"external_ids"`
}

func (q *Queries) ListExistingExternalIDs(ctx context.Context, arg ListExistingExternalIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, listExistingExternalIDs, arg.AccountID, arg.ExternalIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var external_id string
		if err := rows.Scan(&external_id); err != nil {
			return nil, err
		}
		items = append(items, external_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listImportedStatementPeriods = `-- name: ListImportedStatementPeriods :many
select
  id,
  account_id::bigint,
  period_start,
  period_end,
  balance_ok
from
  statements
where
  user_id = $1::uuid
  and status = 2
  and account_id = any($2::bigint[])
order by
  account_id,
  period_start,
  id
`

type ListImportedStatementPeriodsParams struct {
	UserID     uuid.UUID `db:"user_id" json:"user_id"`
	AccountIds []int64   `db:"account_ids" json:"account_ids"`
}

type ListImportedStatementPeriodsRow struct {
	ID          int64     `db:"id" json:"id"`
	AccountID   int64     `db:"account_id" json:"account_id"`
	PeriodStart time.Time `db:"period_start" json:"period_start"`
	PeriodEnd   time.Time `db:"period_end" json:"period_end"`
	BalanceOk   *bool     `db:"balance_ok" json:"balance_ok"`
}

func (q *Queries) ListImportedStatementPeriods(ctx context.Context, arg ListImportedStatementPeriodsParams) ([]ListImportedStatementPeriodsRow, error) {
	rows, err := q.db.Query(ctx, listImportedStatementPeriods, arg.UserID, arg.AccountIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListImportedStatementPeriodsRow
	for rows.Next() {
		var i ListImportedStatementPeriodsRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.PeriodStart,
			&i.PeriodEnd,
			&i.BalanceOk,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReconcileCandidates = `-- name: ListReconcileCandidates :many
select
  t.id, t.account_id, t.external_id, t.tx_date, t.tx_amount_cents, t.tx_currency, t.tx_direction, t.tx_desc, t.balance_after_cents, t.balance_currency, t.merchant, t.category_id, t.category_manually_set, t.merchant_manually_set, t.suggestions, t.user_notes, t.foreign_amount_cents, t.foreign_currency, t.exchange_rate, t.created_at, t.updated_at, t.split_from_id, t.forgiven, t.source, t.statement_id,
  (
    coalesce(t.user_notes, '') <> ''
    or exists(select 1 from receipts r where r.transaction_id = t.id)
    or exists(select 1 from transactions s where s.split_from_id = t.id)
  )::boolean as has_user_data,
  exists(select 1 from transactions s where s.split_from_id = t.id)::boolean as has_splits,
  (t.statement_id is not null)::boolean as from_statement
from
  transactions t
where
  t.account_id = $1::bigint
  and t.split_from_id is null
  and (
    (
      t.statement_id is null
      and t.tx_date >= $2::timestamptz
      and t.tx_date < $3::timestamptz
    )
    -- when re-parsing, the statement's own transactions, whatever their date
    or t.statement_id = $4::bigint
  )
order by
  t.tx_date,
  t.id
`

type ListReconcileCandidatesParams struct {
	AccountID   int64     `db:"account_id" json:"account_id"`
	FromDate    time.Time `db:"from_date" json:"from_date"`
	ToDate      time.Time `db:"to_date" json:"to_date"`
	StatementID *int64    `db:"statement_id" json:"statement_id"`
}

type ListReconcileCandidatesRow struct {
	Transaction   Transaction `db:"transaction" json:"transaction"`
	HasUserData   bool        `db:"has_user_data" json:"has_user_data"`
	HasSplits     bool        `db:"has_splits" json:"has_splits"`
	FromStatement bool        `db:"from_statement" json:"from_statement"`
}

func (q *Queries) ListReconcileCandidates(ctx context.Context, arg ListReconcileCandidatesParams) ([]ListReconcileCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listReconcileCandidates,
		arg.AccountID,
		arg.FromDate,
		arg.ToDate,
		arg.StatementID,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReconcileCandidatesRow
	for rows.Next() {
		var i ListReconcileCandidatesRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.AccountID,
			&i.Transaction.ExternalID,
			&i.Transaction.TxDate,
			&i.Transaction.TxAmountCents,
			&i.Transaction.TxCurrency,
			&i.Transaction.TxDirection,
			&i.Transaction.TxDesc,
			&i.Transaction.BalanceAfterCents,
			&i.Transaction.BalanceCurrency,
			&i.Transaction.Merchant,
			&i.Transaction.CategoryID,
			&i.Transaction.CategoryManuallySet,
			&i.Transaction.MerchantManuallySet,
			&i.Transaction.Suggestions,
			&i.Transaction.UserNotes,
			&i.Transaction.ForeignAmountCents,
			&i.Transaction.ForeignCurrency,
			&i.Transaction.ExchangeRate,
			&i.Transaction.CreatedAt,
			&i.Transaction.UpdatedAt,
			&i.Transaction.SplitFromID,
			&i.Transaction.Forgiven,
			&i.Transaction.Source,
			&i.Transaction.StatementID,
			&i.HasUserData,
			&i.HasSplits,
			&i.FromStatement,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatementDrivenAccounts = `-- name: ListStatementDrivenAccounts :many
select
  id,
  name,
  statements_start,
  statement_release_day,
  closed_at
from
  accounts
where
  owner_id = $1::uuid
  and statement_driven
order by
  name,
  id
`

type ListStatementDrivenAccountsRow struct {
	ID                  int64      `db:"id" json:"id"`
	Name                string     `db:"name" json:"name"`
	StatementsStart     *time.Time `db:"statements_start" json:"statements_start"`
	StatementReleaseDay *int16     `db:"statement_release_day" json:"statement_release_day"`
	ClosedAt            *time.Time `db:"closed_at" json:"closed_at"`
}

func (q *Queries) ListStatementDrivenAccounts(ctx context.Context, userID uuid.UUID) ([]ListStatementDrivenAccountsRow, error) {
	rows, err := q.db.Query(ctx, listStatementDrivenAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatementDrivenAccountsRow
	for rows.Next() {
		var i ListStatementDrivenAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.StatementsStart,
			&i.StatementReleaseDay,
			&i.ClosedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStatements = `-- name: ListStatements :many
select
  s.id, s.user_id, s.account_id, s.status, s.file_path, s.file_hash, s.file_name, s.parser, s.bank, s.account_type, s.account_number, s.period_start, s.period_end, s.currency, s.opening_balance_cents, s.closing_balance_cents, s.line_count, s.parsed, s.created_at, s.imported_at, s.balance_ok,
  a.name as account_name
from
  statements s
  left join accounts a on a.id = s.account_id
where
  s.user_id = $1::uuid
  and (
    $2::bigint is null
    or s.account_id = $2::bigint
  )
  and (
    $3::smallint is null
    or s.status = $3::smallint
  )
order by
  s.period_start desc,
  s.id desc
`

type ListStatementsParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	AccountID *int64    `db:"account_id" json:"account_id"`
	Status    *int16    `db:"status" json:"status"`
}

type ListStatementsRow struct {
	Statement   Statement `db:"statement" json:"statement"`
	AccountName *string   `db:"account_name" json:"account_name"`
}

func (q *Queries) ListStatements(ctx context.Context, arg ListStatementsParams) ([]ListStatementsRow, error) {
	rows, err := q.db.Query(ctx, listStatements, arg.UserID, arg.AccountID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStatementsRow
	for rows.Next() {
		var i ListStatementsRow
		if err := rows.Scan(
			&i.Statement.ID,
			&i.Statement.UserID,
			&i.Statement.AccountID,
			&i.Statement.Status,
			&i.Statement.FilePath,
			&i.Statement.FileHash,
			&i.Statement.FileName,
			&i.Statement.Parser,
			&i.Statement.Bank,
			&i.Statement.AccountType,
			&i.Statement.AccountNumber,
			&i.Statement.PeriodStart,
			&i.Statement.PeriodEnd,
			&i.Statement.Currency,
			&i.Statement.OpeningBalanceCents,
			&i.Statement.ClosingBalanceCents,
			&i.Statement.LineCount,
			&i.Statement.Parsed,
			&i.Statement.CreatedAt,
			&i.Statement.ImportedAt,
			&i.Statement.BalanceOk,
			&i.AccountName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markStatementImported = `-- name: MarkStatementImported :one
update statements
set
  status = 2,
  account_id = $1::bigint,
  imported_at = now()
where
  id = $2::bigint
  and user_id = $3::uuid
  and status = 1
returning
  id, user_id, account_id, status, file_path, file_hash, file_name, parser, bank, account_type, account_number, period_start, period_end, currency, opening_balance_cents, closing_balance_cents, line_count, parsed, created_at, imported_at, balance_ok
`

type MarkStatementImportedParams struct {
	AccountID int64     `db:"account_id" json:"account_id"`
	ID        int64     `db:"id" json:"id"`
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) MarkStatementImported(ctx context.Context, arg MarkStatementImportedParams) (Statement, error) {
	row := q.db.QueryRow(ctx, markStatementImported, arg.AccountID, arg.ID, arg.UserID)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Status,
		&i.FilePath,
		&i.FileHash,
		&i.FileName,
		&i.Parser,
		&i.Bank,
		&i.AccountType,
		&i.AccountNumber,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Currency,
		&i.OpeningBalanceCents,
		&i.ClosingBalanceCents,
		&i.LineCount,
		&i.Parsed,
		&i.CreatedAt,
		&i.ImportedAt,
		&i.BalanceOk,
	)
	return i, err
}

const updateStatementParse = `-- name: UpdateStatementParse :one
update statements
set
  parser = $1::text,
  bank = $2::text,
  account_type = $3::smallint,
  account_number = $4::text,
  period_start = $5::date,
  period_end = $6::date,
  currency = $7::char(3),
  opening_balance_cents = $8::bigint,
  closing_balance_cents = $9::bigint,
  balance_ok = $10::boolean,
  line_count = $11::int,
  parsed = $12::jsonb
where
  id = $13::bigint
  and user_id = $14::uuid
returning
  id, user_id, account_id, status, file_path, file_hash, file_name, parser, bank, account_type, account_number, period_start, period_end, currency, opening_balance_cents, closing_balance_cents, line_count, parsed, created_at, imported_at, balance_ok
`

type UpdateStatementParseParams struct {
	Parser              string    `db:"parser" json:"parser"`
	Bank                string    `db:"bank" json:"bank"`
	AccountType         int16     `db:"account_type" json:"account_type"`
	AccountNumber       string    `db:"account_number" json:"account_number"`
	PeriodStart         time.Time `db:"period_start" json:"period_start"`
	PeriodEnd           time.Time `db:"period_end" json:"period_end"`
	Currency            string    `db:"currency" json:"currency"`
	OpeningBalanceCents *int64    `db:"opening_balance_cents" json:"opening_balance_cents"`
	ClosingBalanceCents *int64    `db:"closing_balance_cents" json:"closing_balance_cents"`
	BalanceOk           *bool     `db:"balance_ok" json:"balance_ok"`
	LineCount           int32     `db:"line_count" json:"line_count"`
	Parsed              []byte    `db:"parsed" json:"parsed"`
	ID                  int64     `db:"id" json:"id"`
	UserID              uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateStatementParse(ctx context.Context, arg UpdateStatementParseParams) (Statement, error) {
	row := q.db.QueryRow(ctx, updateStatementParse,
		arg.Parser,
		arg.Bank,
		arg.AccountType,
		arg.AccountNumber,
		arg.PeriodStart,
		arg.PeriodEnd,
		arg.Currency,
		arg.OpeningBalanceCents,
		arg.ClosingBalanceCents,
		arg.BalanceOk,
		arg.LineCount,
		arg.Parsed,
		arg.ID,
		arg.UserID,
	)
	var i Statement
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.AccountID,
		&i.Status,
		&i.FilePath,
		&i.FileHash,
		&i.FileName,
		&i.Parser,
		&i.Bank,
		&i.AccountType,
		&i.AccountNumber,
		&i.PeriodStart,
		&i.PeriodEnd,
		&i.Currency,
		&i.OpeningBalanceCents,
		&i.ClosingBalanceCents,
		&i.LineCount,
		&i.Parsed,
		&i.CreatedAt,
		&i.ImportedAt,
		&i.BalanceOk,
	)
	return i, err
}
