// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transfers.sql

package sqlc

import (
	"context"
	"time"

	"github.com/google/uuid"
	nagomi "nagomi-core/internal/gen/nagomi/v1"
)

const countLinkedTransfers = `-- name: CountLinkedTransfers :one
select count(*)
from transfers
where status = 1
  and (out_tx_id = any($1::bigint[]) or in_tx_id = any($1::bigint[]))
`

func (q *Queries) CountLinkedTransfers(ctx context.Context, ids []int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLinkedTransfers, ids)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createTransfer = `-- name: CreateTransfer :exec
insert into transfers (user_id, out_tx_id, in_tx_id, status, method)
values ($1::uuid, $2::bigint, $3::bigint, $4::smallint, $5::smallint)
on conflict (out_tx_id, in_tx_id) do nothing
`

type CreateTransferParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	OutTxID int64     `db:"out_tx_id" json:"out_tx_id"`
	InTxID  int64     `db:"in_tx_id" json:"in_tx_id"`
	Status  int16     `db:"status" json:"status"`
	Method  int16     `db:"method" json:"method"`
}

// never overrides a pair the user already linked or rejected
func (q *Queries) CreateTransfer(ctx context.Context, arg CreateTransferParams) error {
	_, err := q.db.Exec(ctx, createTransfer,
		arg.UserID,
		arg.OutTxID,
		arg.InTxID,
		arg.Status,
		arg.Method,
	)
	return err
}

const deleteSuggestedTransfers = `-- name: DeleteSuggestedTransfers :exec
delete from transfers
where user_id = $1::uuid
  and status = 2
  and (out_tx_id = any($2::bigint[]) or in_tx_id = any($2::bigint[]))
`

type DeleteSuggestedTransfersParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Ids    []int64   `db:"ids" json:"ids"`
}

func (q *Queries) DeleteSuggestedTransfers(ctx context.Context, arg DeleteSuggestedTransfersParams) error {
	_, err := q.db.Exec(ctx, deleteSuggestedTransfers, arg.UserID, arg.Ids)
	return err
}

const getTransactionDateRange = `-- name: GetTransactionDateRange :one
select
  min(t.tx_date)::timestamptz as start_date,
  max(t.tx_date)::timestamptz as end_date
from transactions t
join accounts a on a.id = t.account_id
where a.owner_id = $1::uuid
  and ($2::bigint[] is null or t.id = any($2::bigint[]))
`

type GetTransactionDateRangeParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Ids    []int64   `db:"ids" json:"ids"`
}

type GetTransactionDateRangeRow struct {
	StartDate time.Time `db:"start_date" json:"start_date"`
	EndDate   time.Time `db:"end_date" json:"end_date"`
}

func (q *Queries) GetTransactionDateRange(ctx context.Context, arg GetTransactionDateRangeParams) (GetTransactionDateRangeRow, error) {
	row := q.db.QueryRow(ctx, getTransactionDateRange, arg.UserID, arg.Ids)
	var i GetTransactionDateRangeRow
	err := row.Scan(&i.StartDate, &i.EndDate)
	return i, err
}

const linkTransferManually = `-- name: LinkTransferManually :exec
insert into transfers (user_id, out_tx_id, in_tx_id, status, method)
values ($1::uuid, $2::bigint, $3::bigint, 1, 3)
on conflict (out_tx_id, in_tx_id) do update set status = 1, method = 3
`

type LinkTransferManuallyParams struct {
	UserID  uuid.UUID `db:"user_id" json:"user_id"`
	OutTxID int64     `db:"out_tx_id" json:"out_tx_id"`
	InTxID  int64     `db:"in_tx_id" json:"in_tx_id"`
}

func (q *Queries) LinkTransferManually(ctx context.Context, arg LinkTransferManuallyParams) error {
	_, err := q.db.Exec(ctx, linkTransferManually, arg.UserID, arg.OutTxID, arg.InTxID)
	return err
}

const listLinkedTransfers = `-- name: ListLinkedTransfers :many
select
  tr.id,
  tr.method,
  o.id as out_id,
  o.account_id as out_account_id,
  o.tx_amount_cents as out_amount_cents,
  o.tx_currency as out_currency,
  i.id as in_id,
  i.account_id as in_account_id,
  i.tx_amount_cents as in_amount_cents,
  i.tx_currency as in_currency
from transfers tr
join transactions o on o.id = tr.out_tx_id
join transactions i on i.id = tr.in_tx_id
where tr.status = 1
  and (tr.out_tx_id = any($1::bigint[]) or tr.in_tx_id = any($1::bigint[]))
`

type ListLinkedTransfersRow struct {
	ID             int64  `db:"id" json:"id"`
	Method         int16  `db:"method" json:"method"`
	OutID          int64  `db:"out_id" json:"out_id"`
	OutAccountID   int64  `db:"out_account_id" json:"out_account_id"`
	OutAmountCents int64  `db:"out_amount_cents" json:"out_amount_cents"`
	OutCurrency    string `db:"out_currency" json:"out_currency"`
	InID           int64  `db:"in_id" json:"in_id"`
	InAccountID    int64  `db:"in_account_id" json:"in_account_id"`
	InAmountCents  int64  `db:"in_amount_cents" json:"in_amount_cents"`
	InCurrency     string `db:"in_currency" json:"in_currency"`
}

// the linked transfer of each given transaction, with both sides' amounts
func (q *Queries) ListLinkedTransfers(ctx context.Context, ids []int64) ([]ListLinkedTransfersRow, error) {
	rows, err := q.db.Query(ctx, listLinkedTransfers, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLinkedTransfersRow
	for rows.Next() {
		var i ListLinkedTransfersRow
		if err := rows.Scan(
			&i.ID,
			&i.Method,
			&i.OutID,
			&i.OutAccountID,
			&i.OutAmountCents,
			&i.OutCurrency,
			&i.InID,
			&i.InAccountID,
			&i.InAmountCents,
			&i.InCurrency,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferAccounts = `-- name: ListTransferAccounts :many
select a.id, a.name, a.bank, a.friendly_name, a.aliases, a.account_type
from accounts a
where a.owner_id = $1::uuid
  and a.account_type != 6
`

type ListTransferAccountsRow struct {
	ID           int64              `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Bank         string             `db:"bank" json:"bank"`
	FriendlyName *string            `db:"friendly_name" json:"friendly_name"`
	Aliases      []string           `db:"aliases" json:"aliases"`
	AccountType  nagomi.AccountType `db:"account_type" json:"account_type"`
}

func (q *Queries) ListTransferAccounts(ctx context.Context, userID uuid.UUID) ([]ListTransferAccountsRow, error) {
	rows, err := q.db.Query(ctx, listTransferAccounts, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransferAccountsRow
	for rows.Next() {
		var i ListTransferAccountsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Bank,
			&i.FriendlyName,
			&i.Aliases,
			&i.AccountType,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferCandidates = `-- name: ListTransferCandidates :many
select
  t.id,
  t.account_id,
  t.tx_date,
  t.tx_amount_cents,
  t.tx_currency,
  t.tx_direction,
  t.tx_desc,
  t.merchant,
  t.transfer_ref
from transactions t
join accounts a on a.id = t.account_id
where a.owner_id = $1::uuid
  and a.account_type != 6
  and t.split_from_id is null
  and t.tx_date >= $2::timestamptz
  and t.tx_date <= $3::timestamptz
`

type ListTransferCandidatesParams struct {
	UserID    uuid.UUID `db:"user_id" json:"user_id"`
	StartDate time.Time `db:"start_date" json:"start_date"`
	EndDate   time.Time `db:"end_date" json:"end_date"`
}

type ListTransferCandidatesRow struct {
	ID            int64                       `db:"id" json:"id"`
	AccountID     int64                       `db:"account_id" json:"account_id"`
	TxDate        time.Time                   `db:"tx_date" json:"tx_date"`
	TxAmountCents int64                       `db:"tx_amount_cents" json:"tx_amount_cents"`
	TxCurrency    string                      `db:"tx_currency" json:"tx_currency"`
	TxDirection   nagomi.TransactionDirection `db:"tx_direction" json:"tx_direction"`
	TxDesc        *string                     `db:"tx_desc" json:"tx_desc"`
	Merchant      *string                     `db:"merchant" json:"merchant"`
	TransferRef   *string                     `db:"transfer_ref" json:"transfer_ref"`
}

// every transaction in the window that could be one side of a transfer
func (q *Queries) ListTransferCandidates(ctx context.Context, arg ListTransferCandidatesParams) ([]ListTransferCandidatesRow, error) {
	rows, err := q.db.Query(ctx, listTransferCandidates, arg.UserID, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransferCandidatesRow
	for rows.Next() {
		var i ListTransferCandidatesRow
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.TxDate,
			&i.TxAmountCents,
			&i.TxCurrency,
			&i.TxDirection,
			&i.TxDesc,
			&i.Merchant,
			&i.TransferRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransferSuggestions = `-- name: ListTransferSuggestions :many
select o.id, o.account_id, o.external_id, o.tx_date, o.tx_amount_cents, o.tx_currency, o.tx_direction, o.tx_desc, o.balance_after_cents, o.balance_currency, o.merchant, o.category_id, o.category_manually_set, o.merchant_manually_set, o.suggestions, o.user_notes, o.foreign_amount_cents, o.foreign_currency, o.exchange_rate, o.created_at, o.updated_at, o.split_from_id, o.forgiven, o.source, o.statement_id, o.transfer_ref, i.id, i.account_id, i.external_id, i.tx_date, i.tx_amount_cents, i.tx_currency, i.tx_direction, i.tx_desc, i.balance_after_cents, i.balance_currency, i.merchant, i.category_id, i.category_manually_set, i.merchant_manually_set, i.suggestions, i.user_notes, i.foreign_amount_cents, i.foreign_currency, i.exchange_rate, i.created_at, i.updated_at, i.split_from_id, i.forgiven, i.source, i.statement_id, i.transfer_ref
from transfers tr
join transactions o on o.id = tr.out_tx_id
join transactions i on i.id = tr.in_tx_id
where tr.user_id = $1::uuid
  and tr.status = 2
order by o.tx_date desc, tr.id
`

type ListTransferSuggestionsRow struct {
	Transaction   Transaction `db:"transaction" json:"transaction"`
	Transaction_2 Transaction `db:"transaction_2" json:"transaction_2"`
}

func (q *Queries) ListTransferSuggestions(ctx context.Context, userID uuid.UUID) ([]ListTransferSuggestionsRow, error) {
	rows, err := q.db.Query(ctx, listTransferSuggestions, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransferSuggestionsRow
	for rows.Next() {
		var i ListTransferSuggestionsRow
		if err := rows.Scan(
			&i.Transaction.ID,
			&i.Transaction.AccountID,
			&i.Transaction.ExternalID,
			&i.Transaction.TxDate,
			&i.Transaction.TxAmountCents,
			&i.Transaction.TxCurrency,
			&i.Transaction.TxDirection,
			&i.Transaction.TxDesc,
			&i.Transaction.BalanceAfterCents,
			&i.Transaction.BalanceCurrency,
			&i.Transaction.Merchant,
			&i.Transaction.CategoryID,
			&i.Transaction.CategoryManuallySet,
			&i.Transaction.MerchantManuallySet,
			&i.Transaction.Suggestions,
			&i.Transaction.UserNotes,
			&i.Transaction.ForeignAmountCents,
			&i.Transaction.ForeignCurrency,
			&i.Transaction.ExchangeRate,
			&i.Transaction.CreatedAt,
			&i.Transaction.UpdatedAt,
			&i.Transaction.SplitFromID,
			&i.Transaction.Forgiven,
			&i.Transaction.Source,
			&i.Transaction.StatementID,
			&i.Transaction.TransferRef,
			&i.Transaction_2.ID,
			&i.Transaction_2.AccountID,
			&i.Transaction_2.ExternalID,
			&i.Transaction_2.TxDate,
			&i.Transaction_2.TxAmountCents,
			&i.Transaction_2.TxCurrency,
			&i.Transaction_2.TxDirection,
			&i.Transaction_2.TxDesc,
			&i.Transaction_2.BalanceAfterCents,
			&i.Transaction_2.BalanceCurrency,
			&i.Transaction_2.Merchant,
			&i.Transaction_2.CategoryID,
			&i.Transaction_2.CategoryManuallySet,
			&i.Transaction_2.MerchantManuallySet,
			&i.Transaction_2.Suggestions,
			&i.Transaction_2.UserNotes,
			&i.Transaction_2.ForeignAmountCents,
			&i.Transaction_2.ForeignCurrency,
			&i.Transaction_2.ExchangeRate,
			&i.Transaction_2.CreatedAt,
			&i.Transaction_2.UpdatedAt,
			&i.Transaction_2.SplitFromID,
			&i.Transaction_2.Forgiven,
			&i.Transaction_2.Source,
			&i.Transaction_2.StatementID,
			&i.Transaction_2.TransferRef,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransfersTouching = `-- name: ListTransfersTouching :many
select id, out_tx_id, in_tx_id, status, method
from transfers
where user_id = $1::uuid
  and (out_tx_id = any($2::bigint[]) or in_tx_id = any($2::bigint[]))
`

type ListTransfersTouchingParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	Ids    []int64   `db:"ids" json:"ids"`
}

type ListTransfersTouchingRow struct {
	ID      int64 `db:"id" json:"id"`
	OutTxID int64 `db:"out_tx_id" json:"out_tx_id"`
	InTxID  int64 `db:"in_tx_id" json:"in_tx_id"`
	Status  int16 `db:"status" json:"status"`
	Method  int16 `db:"method" json:"method"`
}

func (q *Queries) ListTransfersTouching(ctx context.Context, arg ListTransfersTouchingParams) ([]ListTransfersTouchingRow, error) {
	rows, err := q.db.Query(ctx, listTransfersTouching, arg.UserID, arg.Ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListTransfersTouchingRow
	for rows.Next() {
		var i ListTransfersTouchingRow
		if err := rows.Scan(
			&i.ID,
			&i.OutTxID,
			&i.InTxID,
			&i.Status,
			&i.Method,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const rejectTransfer = `-- name: RejectTransfer :execrows
update transfers
set status = 3
where user_id = $1::uuid
  and status = 1
  and (out_tx_id = $2::bigint or in_tx_id = $2::bigint)
`

type RejectTransferParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	TxID   int64     `db:"tx_id" json:"tx_id"`
}

func (q *Queries) RejectTransfer(ctx context.Context, arg RejectTransferParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectTransfer, arg.UserID, arg.TxID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const rejectTransferPair = `-- name: RejectTransferPair :execrows
update transfers
set status = 3
where user_id = $1::uuid
  and status in (1, 2)
  and ((out_tx_id = $2::bigint and in_tx_id = $3::bigint) or (out_tx_id = $3::bigint and in_tx_id = $2::bigint))
`

type RejectTransferPairParams struct {
	UserID uuid.UUID `db:"user_id" json:"user_id"`
	A      int64     `db:"a" json:"a"`
	B      int64     `db:"b" json:"b"`
}

func (q *Queries) RejectTransferPair(ctx context.Context, arg RejectTransferPairParams) (int64, error) {
	result, err := q.db.Exec(ctx, rejectTransferPair, arg.UserID, arg.A, arg.B)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setTransferRef = `-- name: SetTransferRef :one
update transactions t
set transfer_ref = $1::text
from accounts a
where a.id = t.account_id
  and a.owner_id = $2::uuid
  and t.account_id = $3::bigint
  and t.external_id = $4::text
  and t.transfer_ref is null
returning t.id
`

type SetTransferRefParams struct {
	TransferRef string    `db:"transfer_ref" json:"transfer_ref"`
	UserID      uuid.UUID `db:"user_id" json:"user_id"`
	AccountID   int64     `db:"account_id" json:"account_id"`
	ExternalID  string    `db:"external_id" json:"external_id"`
}

// fills in the reference on a row imported before its importer sent one
func (q *Queries) SetTransferRef(ctx context.Context, arg SetTransferRefParams) (int64, error) {
	row := q.db.QueryRow(ctx, setTransferRef,
		arg.TransferRef,
		arg.UserID,
		arg.AccountID,
		arg.ExternalID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
