-- +goose Up
CREATE TABLE statements (
  id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id               UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  -- null until the import is committed
  account_id            BIGINT REFERENCES accounts(id) ON DELETE CASCADE,
  -- values mirror nagomi.v1.StatementStatus
  status                SMALLINT NOT NULL,
  file_path             TEXT NOT NULL,
  file_hash             TEXT NOT NULL,
  file_name             TEXT NOT NULL DEFAULT '',
  parser                TEXT NOT NULL,
  bank                  TEXT NOT NULL,
  account_type          SMALLINT NOT NULL,
  account_number        TEXT NOT NULL,
  period_start          DATE NOT NULL,
  period_end            DATE NOT NULL,
  currency              CHAR(3) NOT NULL,
  opening_balance_cents BIGINT,
  closing_balance_cents BIGINT,
  line_count            INT NOT NULL,
  -- nagomi.v1.ParsedStatement as protojson, so commit and re-import never re-parse
  parsed                JSONB NOT NULL,
  created_at            TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  imported_at           TIMESTAMPTZ,
  UNIQUE (user_id, file_hash)
);

CREATE INDEX idx_statements_account ON statements(account_id, period_start);
CREATE INDEX idx_statements_pending ON statements(created_at) WHERE status = 1;

ALTER TABLE transactions
  ADD COLUMN statement_id BIGINT REFERENCES statements(id) ON DELETE SET NULL;

CREATE INDEX idx_transactions_statement ON transactions(statement_id) WHERE statement_id IS NOT NULL;

-- +goose Down
DROP INDEX IF EXISTS idx_transactions_statement;
ALTER TABLE transactions DROP COLUMN statement_id;
DROP TABLE IF EXISTS statements;
