-- +goose Up
-- set by an importer when it knows two rows are one transfer
ALTER TABLE transactions ADD COLUMN transfer_ref TEXT;
CREATE INDEX idx_tx_transfer_ref ON transactions (transfer_ref) WHERE transfer_ref IS NOT NULL;

-- pairs of transactions that move money between a user's own accounts.
-- status: 1 linked, 2 suggested, 3 rejected. method: 1 reference, 2 matched, 3 manual
CREATE TABLE transfers (
  id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id    UUID        NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  out_tx_id  BIGINT      NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  in_tx_id   BIGINT      NOT NULL REFERENCES transactions(id) ON DELETE CASCADE,
  status     SMALLINT    NOT NULL CHECK (status BETWEEN 1 AND 3),
  method     SMALLINT    NOT NULL CHECK (method BETWEEN 1 AND 3),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (out_tx_id, in_tx_id),
  CHECK (out_tx_id <> in_tx_id)
);

-- a transaction is part of at most one linked transfer
CREATE UNIQUE INDEX ux_transfers_out_linked ON transfers (out_tx_id) WHERE status = 1;
CREATE UNIQUE INDEX ux_transfers_in_linked ON transfers (in_tx_id) WHERE status = 1;
CREATE INDEX idx_transfers_in ON transfers (in_tx_id);
CREATE INDEX idx_transfers_user_status ON transfers (user_id, status);

-- the amount each transaction contributes to income and spending. a linked
-- transfer only counts what was lost or gained on the way, and nothing when
-- the sides are in different currencies.
CREATE VIEW transaction_report AS
SELECT
  t.id,
  (lo.id IS NOT NULL OR li.id IS NOT NULL)::BOOLEAN AS is_transfer,
  CASE
    WHEN lo.id IS NOT NULL THEN
      CASE WHEN i.tx_currency = t.tx_currency THEN GREATEST(t.tx_amount_cents - i.tx_amount_cents, 0) ELSE 0 END
    WHEN li.id IS NOT NULL THEN
      CASE WHEN o.tx_currency = t.tx_currency THEN GREATEST(t.tx_amount_cents - o.tx_amount_cents, 0) ELSE 0 END
    ELSE t.tx_amount_cents
  END::BIGINT AS report_cents
FROM transactions t
LEFT JOIN transfers lo ON lo.out_tx_id = t.id AND lo.status = 1
LEFT JOIN transactions i ON i.id = lo.in_tx_id
LEFT JOIN transfers li ON li.in_tx_id = t.id AND li.status = 1
LEFT JOIN transactions o ON o.id = li.out_tx_id;

-- +goose Down
DROP VIEW transaction_report;
DROP TABLE transfers;
ALTER TABLE transactions DROP COLUMN transfer_ref;
